#!/usr/bin/env python3
from pathlib import Path
import argparse
import importlib.util
import sys

ROOT = Path(__file__).resolve().parents[2]
RESEARCH = ROOT / "research/stage1_filing_bound"
OUTPUT = ROOT / "paper1/data/stage1_attributes.adoc"

spec = importlib.util.spec_from_file_location(
    "frontier48",
    RESEARCH / "48_income_tax_stage1_untracked_frontier.py",
)
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)


def fmt_int(x):
    return f"{int(round(x)):,}"


def build():
    v = m.frontier47.overlap.load_inputs()
    d46, _ = m.frontier47.overlap.compute(v)
    s47, _ = m.frontier47.compute(v)
    s48 = m.compute(v)

    attrs = {
        "stage1-final-return-filers":
            fmt_int(v["nta_final_return_filers_2024"]),
        "stage1-candidate-upper":
            fmt_int(d46["candidate_person_upper"]),
        "stage1-mother-benchmark":
            fmt_int(d46["f71561_mother_person_benchmark"]),
        "stage1-nominal-outside":
            fmt_int(d46["nominal_outside_person_benchmark"]),
        "stage1-nominal-overlap":
            fmt_int(d46["nominal_return_filer_overlap_benchmark"]),
        "stage1-nominal-rate-pct":
            f'{100*d46["c0_pretracked_participation_benchmark"]:.4f}',
        "stage1-tracked-allowance":
            fmt_int(s47["tracked_mismatch_allowance"]),
        "stage1-residual-benchmark":
            fmt_int(s48["residual_benchmark_after_tracked_allowance"]),
        "stage1-robustness-rate-cu0-pct":
            f'{100*s48["robustness_rate_at_C_U_0"]:.5f}',
    }

    lines = [
        "// Generated by paper1/scripts/generate_stage1_attributes.py",
    ]
    lines.extend(f":{k}: {val}" for k, val in attrs.items())
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    expected = build()

    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("ERROR: stage1_attributes.adoc is stale")
            sys.exit(1)
        print("paper1 stage1 attributes: current")
        return

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
