#!/usr/bin/env python3
from pathlib import Path
import csv
import hashlib

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data/raw"
OUT = ROOT / "data/source_catalog.csv"

# Every file under data/raw must appear exactly once here.
SOURCES = [
    ("ESTAT-7141-1-2024","Statistics Bureau of Japan","2024 NSFCW table 7-141-1: household members by main annual-income type and equivalized disposable-income class/decile","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040490407&fileKind=0","estat/000040490407.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040490407; table 7-141-1; main annual-income type columns BZ:CD used as within-NSFCW rank diagnostics","RAW_OFFICIAL"),
    ("ESTAT-7171-2024","Statistics Bureau of Japan","2024 NSFCW table 7-171: equivalized annual-income quantiles by main annual-income type and other characteristics","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040490427&fileKind=0","estat/000040490427.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040490427; table 7-171; OECD-new equivalized-disposable-income quantiles used as within-NSFCW diagnostic","RAW_OFFICIAL"),
    ("ESTAT-7153-1-2024","Statistics Bureau of Japan","2024 NSFCW table 7-153-1: equivalized annual income by decile and income component","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040490416&fileKind=0","estat/000040490416.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040490416; table 7-153-1","RAW_OFFICIAL"),
    ("ESTAT-7156-1-2024","Statistics Bureau of Japan","2024 NSFCW table 7-156-1: household type x equivalized disposable-income class/decile x equivalized annual-income component","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040490419&fileKind=0","estat/000040490419.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040490419; table 7-156-1","RAW_OFFICIAL"),
    ("ESTAT-7155-1-2024","Statistics Bureau of Japan","2024 NSFCW table 7-155-1: sex x age class x equivalized disposable-income class/decile x equivalized annual-income component","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040490418&fileKind=0","estat/000040490418.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040490418; table 7-155-1; F71551","RAW_OFFICIAL"),
    ("ESTAT-7191-1-2024","Statistics Bureau of Japan","2024 NSFCW table 7-191-1: household members by sex, age, household size, head employment, income and asset classes","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040490431&fileKind=0","estat/000040490431.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040490431; table 7-191-1; F71911","RAW_OFFICIAL"),
    ("ESTAT-LOCAL-PUBLIC-SALARY-2024-T1","Ministry of Internal Affairs and Communications","2024 Local Public Employee Salary Survey Table 1 - staff counts by public-body category","https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040324410&fileKind=0","estat/000040324410.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","e-Stat statInfId=000040324410; Table 1; all local public bodies; total, regular-category subtotal, general staff, education public employees, police and temporary staff","RAW_OFFICIAL"),
    ("ESTAT-LOCAL-PUBLIC-SALARY-2024-METADATA","Ministry of Internal Affairs and Communications","2024 Local Public Employee Salary Survey e-Stat metadata","https://www.e-stat.go.jp/stat-search/files?bunya_l=13&cycle=0&layout=datalist&page=1&result_page=1&tclass1=000001226528&tclass2val=0&toukei=00200212&tstat=000001226526","estat/estat_2024_local_public_salary_survey_metadata.html","text/html","e-Stat metadata snapshot; 2024 Local Public Employee Salary Survey; Table 1 staff counts; official-statistics scope metadata","RAW_OFFICIAL_METADATA"),
    ("JINJI-2024-PUBLIC-SALARY-SURVEY-SUMMARY","National Personnel Authority","2024 National Public Employee Salary Survey - staff count and average pay summary","https://www.jinji.go.jp/content/000012099.csv","jinji_2024_national_public_staff_summary.csv","text/csv","CP932 CSV; all pay schedules 250,434 covered employees; average age and monthly pay by pay schedule","RAW_OFFICIAL"),
    ("JINJI-2024-PUBLIC-SALARY-SURVEY-T1","National Personnel Authority","2024 National Public Employee Salary Survey Table 1 - persons by pay schedule, sex and age","https://www.jinji.go.jp/content/000012101.csv","jinji_2024_national_public_staff_by_pay_schedule_age.csv","text/csv","CP932 CSV; Table 1; all pay schedules 250,434 persons and pay-schedule/sex/age decomposition","RAW_OFFICIAL"),
    ("JINJI-2024-PUBLIC-SALARY-SURVEY-RESULTS","National Personnel Authority","2024 National Public Employee Salary Survey - official results and scope","https://www.jinji.go.jp/content/000012098.pdf","jinji_2024_national_public_salary_survey_results.pdf","application/pdf","Official 2024 survey results; 2024-04-01 persons=250,434; scope is employees covered by specified national pay statutes with stated exclusions including new hires, certain re-employed staff, overseas/leave/dispatch categories","RAW_OFFICIAL_METADATA"),
    ("STAT-F71561-DESIGN","Statistics Bureau of Japan","2024 National Survey of Family Income, Consumption and Wealth sample design","https://www.stat.go.jp/data/zenkokukakei/2024/pdf/hyohon2024.pdf","statistics_bureau/2024_nsfcw_sample_design.pdf","application/pdf","Section II; Table 4; 2020 Census results rearranged to municipalities as of 2024-01-01","RAW_OFFICIAL"),
    ("STAT-CENSUS-2020-SUMMARY","Statistics Bureau of Japan","Population and Households of Japan 2020 - overview","https://www.stat.go.jp/english/data/kokusei/2020/summary/pdf/all.pdf","statistics_bureau/2020_population_census_summary_en.pdf","application/pdf","Summary p.2 / PDF p.5; total population 126,146,099","RAW_OFFICIAL"),
    ("STAT-CENSUS-2020-BASIC","Statistics Bureau of Japan","2020 Population Census basic complete tabulation - results overview","https://www.stat.go.jp/data/kokusei/2020/kekka/pdf/outline_01.pdf","statistics_bureau/2020_population_census_basic_complete_summary.pdf","application/pdf","General-household persons and one-person general households; cross-check against Census Report Table 7-2","RAW_OFFICIAL"),
    ("STAT-MIGRATION-2024","Statistics Bureau of Japan","Report on Internal Migration in Japan 2024 - summary","https://www.stat.go.jp/data/idou/2024np/jissu/pdf/gaiyou.pdf","statistics_bureau/2024_basic_resident_register_migration_summary.pdf","application/pdf","Table 1; gross international inflow, 2020-2024","RAW_OFFICIAL"),
    ("ISHIKAWA-CENSUS-2020","Ishikawa Prefecture","2020 Population Census basic tabulation summary - Ishikawa","https://toukei.pref.ishikawa.lg.jp/dl/4461/R2census_jinkou.pdf","ishikawa/2020_population_census_summary.pdf","application/pdf","Municipal population and general-household-person tables for Wajima, Suzu, Anamizu and Noto","RAW_OFFICIAL"),
    ("NTA-R06","National Tax Agency","FY2024 National Tax Agency Annual Statistics Report","https://www.nta.go.jp/publication/statistics/kokuzeicho/r06/R06.pdf","nta/nta_fy2024_annual_statistics.pdf","application/pdf","PDF pp.71-72 / printed pp.61-62; Table 2-2(1) exact filed-or-processed persons by primary income-earner category; PDF p.55 / printed p.46 Table 2-1(1) Final return processing row 23,090,075; do not equate this row to the separate press-release submitted-return count","RAW_OFFICIAL"),
    ("NTA-FY2024-WITHHOLDING-STATUS","National Tax Agency","FY2024 Withholding Income Tax Statistics - taxation status","https://www.nta.go.jp/publication/statistics/kokuzeicho/gensen2024/gensen/pdf/03_kazeijokyo.xlsx","nta/nta_fy2024_withholding_income_tax_status.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet (6)(7)...給与退職所得; Table (7) employment/retirement income taxation status; salary/wages/bonus payment and withholding amounts split into Public offices, Others and Total; no person counts","RAW_OFFICIAL"),
    ("NTA-WITHHOLDING-LONG-TERM","National Tax Agency","Long-term Withholding Income Tax Statistics","https://www.nta.go.jp/publication/statistics/kokuzeicho/jikeiretsu/xls/02.xlsx","nta/nta_withholding_long_term_series.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet ５ 給与所得; public-office and other salary payment amounts 1948-2024; person columns available through 2006 and shown as dash from 2007 onward; note states person fields from 1991 onward are sample-survey estimates","RAW_OFFICIAL"),
    ("NTA-WITHHOLDING-2006-STATUS","National Tax Agency","2006 Withholding Income Tax Statistics - taxation status","https://www.nta.go.jp/publication/statistics/kokuzeicho/gensen2006/kazeijyokyo.pdf","nta/nta_2006_withholding_tax_status.pdf","application/pdf","PDF p.4 / printed p.118; Table (7) publishes Public Offices/Others/Total person estimates alongside payment and withholding amounts; persons include short-term/temporary staff and 1991+ person fields are sample-survey estimates per long-term note","RAW_OFFICIAL"),
    ("NTA-WITHHOLDING-2007-STATUS","National Tax Agency","2007 Withholding Income Tax Statistics - taxation status","https://www.nta.go.jp/publication/statistics/kokuzeicho/gensen2007/pdf/gensen.pdf","nta/nta_2007_withholding_tax_status.pdf","application/pdf","PDF p.4 / printed p.120; Table (7) retains Public Offices/Others/Total payment and withholding amounts but no longer publishes person columns; first year of published person-series discontinuity","RAW_OFFICIAL"),
    ("NTA-2024-PROCESSING-STATUS","National Tax Agency","2024 Self-Assessment Income Tax - filing returns and cases processed","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkoku2024/pdf/02_kazeijokyo.pdf","nta/nta_2024_self_assessment_processing_status.pdf","application/pdf","PDF pp.1-6 / Table 2-1(1) parts 1-6; exact 2024 Final return, amended return, correction/determination and filed-or-processed totals for all five income-earner categories plus total; official scope is cases filed or processed by 2025-03-31, taxation status as of 2025-06-30","RAW_OFFICIAL"),
    ("NTA-2024-ANNUAL-T23-INCOME-TYPE","National Tax Agency","2024 Annual Statistics Table 2-3 - persons and income by income type","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkoku2024/pdf/02_syotokushu.pdf","nta/nta_2024_annual_income_type_persons_amounts.pdf","application/pdf","PDF p.1; employment-income row gives all/main/secondary persons split by positive self-assessed balance and refund; complete-survey administrative statistics","RAW_OFFICIAL"),
    ("NTA-2024-ANNUAL-TABLE-NOTES","National Tax Agency","2024 Annual Statistics self-assessment income-tax table notes","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkoku2024/pdf/02_tokeihyo.pdf","nta/nta_2024_annual_self_assessment_table_notes.pdf","application/pdf","PDF pp.1-2; complete-survey scope and distinct aggregation definitions for Tables 2-1/2-2 versus Table 2-3, including worked example","RAW_OFFICIAL_METADATA"),
    ("NTA-2024-RETURN-PRESS-T31","National Tax Agency","2024 final-return filing situation press release - Table 3-1 primary income category","https://www.nta.go.jp/topics/pdf/0025005-063.pdf","nta/nta_2024_final_return_press_table31.pdf","application/pdf","PDF p.15 / printed p.14; Table 3-1; counts are based on return forms submitted by 2025-03-31 and displayed in thousand persons; note warns totals and components can differ due to rounding","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-SAMPLE","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/pdf/R06.pdf","nta/nta_2024_shinkoku_sample_survey.pdf","application/pdf","target population: persons with positive self-assessed tax; five primary income categories; retained as frame-definition/cross-check source","RAW_OFFICIAL"),
    ("NTA-SHINKOKU-JIKEIRETSU-T1-XLSX","National Tax Agency","Long-term Sample Survey for Self-Assessment Income Tax Table 1 - Summary","https://www.nta.go.jp/publication/statistics/kokuzeicho/jikeiretsu/xls01/s1.xlsx","nta/nta_jikeiretsu_shinkoku_sample_table1.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Long-term series Table 1; 2024 row 79; total persons, income, deductions, calculated tax, credits, withholding and self-assessed balance","RAW_OFFICIAL"),
    ("NTA-SHINKOKU-JIKEIRETSU-T2-XLSX","National Tax Agency","Long-term Sample Survey for Self-Assessment Income Tax Table 2 - Income Class Series","https://www.nta.go.jp/publication/statistics/kokuzeicho/jikeiretsu/xls01/s2.xlsx","nta/nta_jikeiretsu_shinkoku_sample_table2.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Long-term series Table 2; sheets include 納税者数（合計）, 算出税額（合計）, 税額控除額（合計）, 源泉徴収税額（合計）, 申告納税額（合計）; 2024 total in AE79","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T1-XLSX","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 1 - Summary Table","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/xls/R06_01.xlsx","nta/nta_2024_shinkoku_sample_table1_summary.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet 第１表; 25 total-income classes and five primary income-earner categories; calculated tax, tax credits, withholding persons/amount, and self-assessed balance","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T4-XLSX","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 4 - Tax Credits Table","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/xls/R06_04.xlsx","nta/nta_2024_shinkoku_sample_table4_tax_credits.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet 第４表; tax-credit persons and amounts by the same 25 income classes and five primary income-earner categories","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T5-XLSX","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 5 - Withholding Tax Table","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/xls/R06_05.xlsx","nta/nta_2024_shinkoku_sample_table5_withholding.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet 第５表; source-withholding persons and amounts by the same 25 income classes and five primary income-earner categories, including salary/non-salary/pension components","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T7-XLSX","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 7 - Salary Receipt Class Table","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/xls/R06_07.xlsx","nta/nta_2024_shinkoku_sample_table7_salary_receipts.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet 第７表; salary-receipt classes by five income-earner categories plus total; salary-receipt persons/amount and salary-source-withholding persons/amount within the positive-self-assessed-balance survey target","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T7-PDF","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 7 - Salary Receipt Class Table PDF","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/pdf/R06_07.pdf","nta/nta_2024_shinkoku_sample_table7_salary_receipts.pdf","application/pdf","PDF p.1 / printed p.80; visual cross-check for Table 7 XLSX; sample-survey estimates and salary-receipt threshold semantics","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T2-XLSX","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 2 - Income Type Table","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/xls/R06_02.xlsx","nta/nta_2024_shinkoku_sample_table2.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Sheet 第２表; total-income-class rows and five primary income-earner category blocks; machine-readable source for positive-self-assessed-balance cross-tab","RAW_OFFICIAL"),
    ("NTA-2024-SHINKOKU-T2-PDF","National Tax Agency","2024 Sample Survey for Self-Assessment Income Tax Table 2 - Income Type Table PDF","https://www.nta.go.jp/publication/statistics/kokuzeicho/shinkokuhyohon2024/pdf/R06_02.pdf","nta/nta_2024_shinkoku_sample_table2.pdf","application/pdf","PDF printed pp.35,39,43 anchor business / real-estate+salary / miscellaneous+other blocks; visual cross-check for XLSX extraction","RAW_OFFICIAL"),
    ("NTA-MINKAN-2024-T1","National Tax Agency","2024 Private Salary Survey Table 1 - salary earners, salary amount and tax","https://www.nta.go.jp/publication/statistics/kokuzeicho/minkan2024/excel/R06_01.xlsx","nta/nta_minkan2024_table1_salary_persons_amount_tax.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Table 1 sheet その1; 2024 salary-earner stock/average-monthly estimates, annual salary amount and withholding tax; survey target restricted to employees of private withholding agents at year end","RAW_OFFICIAL"),
    ("NTA-MINKAN-2024-T16","National Tax Agency","2024 Private Salary Survey Table 16 - taxpayers/non-taxpayers by salary class","https://www.nta.go.jp/publication/statistics/kokuzeicho/minkan2024/excel/R06_16.xlsx","nta/nta_minkan2024_table16_taxpayer_nontaxpayer.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Table 16; sheets その1-その4; salary-class taxpayer/non-taxpayer counts split by year-end adjustment and secondary-payroll (乙欄) exclusion","RAW_OFFICIAL"),
    ("NTA-MINKAN-2024-T19","National Tax Agency","2024 Private Salary Survey Table 19 - salary earners without year-end adjustment","https://www.nta.go.jp/publication/statistics/kokuzeicho/minkan2024/excel/R06_19.xlsx","nta/nta_minkan2024_table19_not_year_end_adjusted.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Table 19; sheets その1, その2, その3・その4; reason split for no year-end adjustment and full-year salary receipts above 20 million yen","RAW_OFFICIAL"),
    ("NTA-2024-SALARY-FILING-REQUIREMENT","National Tax Agency","2024 filing guidance - salary earners required to file a final return","https://www.keisan.nta.go.jp/r6yokuaru/cat2/cat21/cat213/cid405.html","nta/nta_2024_salary_final_return_requirement.html","text/html","2024 filing guidance: annual salary receipts above 20 million yen are in principle subject to final-return filing; page also states the refund-return caveat","RAW_OFFICIAL_METADATA"),
    ("NTA-NAGOYA-2024-SHINKOKU-21-XLSX","National Tax Agency - Nagoya Regional Taxation Bureau","2024 Self-Assessment Income Tax regional Table 2-1 - taxation status","https://www.nta.go.jp/about/organization/nagoya/statistics/r06/xls/2-1.xlsx","nta/nta_nagoya_2024_shinkoku_2-1.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Regional Table 2-1; sheets include filing/processing status and tax-office taxation status; processing status is not cross-tabulated by salary-receipt threshold or year-end-adjustment status","RAW_OFFICIAL"),
    ("NTA-NAGOYA-2024-SHINKOKU-22-XLSX","National Tax Agency - Nagoya Regional Taxation Bureau","2024 Self-Assessment Income Tax regional Table 2-2 - income-class persons","https://www.nta.go.jp/about/organization/nagoya/statistics/r06/xls/2-2.xlsx","nta/nta_nagoya_2024_shinkoku_2-2.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Regional Table 2-2; income-class and tax-office person tables including salary-primary categories; total-net-income classes are not salary-receipt classes and do not add year-end-adjustment or processing-status cross-tabs","RAW_OFFICIAL"),
    ("NTA-MINKAN-METHODOLOGY","National Tax Agency","Private Salary Survey methodology and terminology","https://www.nta.go.jp/publication/statistics/kokuzeicho/minkan/top.htm","nta/nta_private_salary_survey_methodology.html","text/html","Survey target includes private-sector salary earners regardless of tax; terminology defines 納税者 as salary earners with positive source-withheld income tax; year-end adjustment/tax-unit cautions used for external diagnostic","RAW_OFFICIAL_METADATA"),
    ("NTA-MINKAN-2024-T17","National Tax Agency","2024 Private Salary Survey Table 17 - deductions by salary class","https://www.nta.go.jp/publication/statistics/kokuzeicho/minkan2024/excel/R06_17.xlsx","nta/nta_minkan2024_table17.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Table 17; sheets その1の1/その1の2/その2の1 (total); year-end-adjusted full-year employees","RAW_OFFICIAL"),
    ("NTA-INFO-EXCHANGE-2024","National Tax Agency","FY2024 status of information exchange under tax treaties","https://www.nta.go.jp/information/release/pdf/0026001-016.pdf","nta/nta_fy2024_tax_treaty_information_exchange.pdf","application/pdf","Non-resident statutory-report information exchange count; scale diagnostic only","RAW_OFFICIAL"),
    ("NTA-NONRESIDENT-GUIDANCE","National Tax Agency","Tax Answer No.1926 - non-residents with Japanese domestic-source income","https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1926.htm","nta/nonresident_domestic_source_guidance.html","text/html","Legal/source-coverage audit; no person count extracted","RAW_OFFICIAL"),
    ("NTA-2026-TAX-REFORM","National Tax Agency","April 2026 outline of withholding income-tax reform","https://www.nta.go.jp/publication/pamph/gensen/2026kaisei.pdf","nta/nta_2026_withholding_tax_reform.pdf","application/pdf","p.1: 2026-2029 basic deduction and employment-income deduction special rules; p.2 onward related reforms","RAW_OFFICIAL"),
    ("NTA-2026-INCOME-TAX","National Tax Agency","Income tax mechanism - 2026","https://www.nta.go.jp/publication/pamph/koho/kurashi/html/01_1.htm","nta/nta_2026_income_tax_mechanism.html","text/html","2026 basic-deduction table and progressive income-tax rate table","RAW_OFFICIAL"),
    ("NTA-SALARY-DEDUCTION-1410","National Tax Agency","Tax Answer No.1410 - employment income deduction","https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1410.htm","nta/nta_income_tax_answer_1410_salary_deduction.html","text/html","standard employment-income deduction schedule; combined with 2026 special rule source for 2026-2029","RAW_OFFICIAL"),
    ("NTA-INCOME-TAX-RATE-2260","National Tax Agency","Tax Answer No.2260 - income tax rates","https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/2260.htm","nta/nta_income_tax_answer_2260_rates.html","text/html","ordinary national income-tax progressive quick table; rates unchanged for the 2026 ordinary schedule","RAW_OFFICIAL"),
    ("NTA-2026-PENSION-TAX","National Tax Agency","Elderly people and tax (pensions) - 2026","https://www.nta.go.jp/publication/pamph/koho/kurashi/html/03_1.htm","nta/nta_2026_pension_tax.html","text/html","2026 public-pension miscellaneous-income calculation table by age","RAW_OFFICIAL"),
    ("NTA-2026-PENSION-DETAIL","National Tax Agency","2026 withholding income-tax outline - public pension deduction detail","https://www.nta.go.jp/publication/pamph/gensen/aramashi2026/pdf/06.pdf","nta/nta_2026_public_pension_deduction_detail.pdf","application/pdf","public-pension deduction table by age, pension income, and non-pension income; 10m/20m other-income adjustments","RAW_OFFICIAL"),
    ("NTA-2026-DEPENDENT-DEDUCTION","National Tax Agency","2026 withholding declaration instructions - dependent deduction amounts","https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/gensen/pdf/2026bun_08.pdf","nta/nta_2026_dependent_deduction_amounts.pdf","application/pdf","dependent deduction amounts: general 380k, specified 630k, elderly 480k, co-resident elderly 580k; 2026 form instructions","RAW_OFFICIAL"),
    ("MHLW-VITAL-2020-PAGE","Ministry of Health, Labour and Welfare","2020 Vital Statistics final landing page","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei20/index.html","mhlw/2020_vital_statistics_final_page.html","text/html","Landing-page snapshot linking final tables","RAW_OFFICIAL_METADATA"),
    ("MHLW-VITAL-2020-T1","Ministry of Health, Labour and Welfare","2020 Vital Statistics final - Table 1","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei20/dl/03_h1.pdf","mhlw/2020_vital_table1.pdf","application/pdf","Table 1; births 2020","RAW_OFFICIAL"),
    ("MHLW-VITAL-2020-T2","Ministry of Health, Labour and Welfare","2020 Vital Statistics final - Table 2-1 annual trend","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei20/dl/04_h2-1.pdf","mhlw/2020_vital_trend_table2_1.pdf","application/pdf","Table 2-1 annual trend","RAW_OFFICIAL"),
    ("MHLW-VITAL-2022-PAGE","Ministry of Health, Labour and Welfare","2022 Vital Statistics final landing page","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei22/","mhlw/2022_vital_statistics_final_page.html","text/html","Landing-page snapshot linking final tables","RAW_OFFICIAL_METADATA"),
    ("MHLW-VITAL-2022-T1","Ministry of Health, Labour and Welfare","2022 Vital Statistics final - Table 1","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei22/dl/03_h1.pdf","mhlw/2022_vital_table1.pdf","application/pdf","Table 1; births 2022 and prior-year 2021","RAW_OFFICIAL"),
    ("MHLW-VITAL-2022-T2","Ministry of Health, Labour and Welfare","2022 Vital Statistics final - Table 2-1 annual trend","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei22/dl/04_h2-1.pdf","mhlw/2022_vital_trend_table2_1.pdf","application/pdf","Table 2-1; 2020-2022 annual trend","RAW_OFFICIAL"),
    ("MHLW-VITAL-2024-PAGE","Ministry of Health, Labour and Welfare","2024 Vital Statistics final landing page","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei24/","mhlw/2024_vital_statistics_final_page.html","text/html","Landing-page snapshot linking final tables","RAW_OFFICIAL_METADATA"),
    ("MHLW-VITAL-2024-T1","Ministry of Health, Labour and Welfare","2024 Vital Statistics final - Table 1","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei24/dl/03_h1.pdf","mhlw/2024_vital_table1.pdf","application/pdf","Table 1; births/deaths 2024 and prior-year 2023","RAW_OFFICIAL"),
    ("MHLW-VITAL-2024-T2","Ministry of Health, Labour and Welfare","2024 Vital Statistics final - Table 2 annual trend","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/kakutei24/dl/04_h2.pdf","mhlw/2024_vital_trend_table2.pdf","application/pdf","Table 2 annual trend","RAW_OFFICIAL"),
    ("MHLW-VITAL-2024-ANNUAL-PAGE","Ministry of Health, Labour and Welfare","2024 Vital Statistics annual-summary landing page","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/geppo/nengai24/","mhlw/2024_vital_statistics_annual_summary_page.html","text/html","Landing-page snapshot; comparison only when final data are unavailable","RAW_OFFICIAL_METADATA"),
    ("MHLW-VITAL-2024-ANNUAL-T1","Ministry of Health, Labour and Welfare","2024 Vital Statistics annual-summary Table 1","https://www.mhlw.go.jp/toukei/saikin/hw/jinkou/geppo/nengai24/dl/h1.pdf","mhlw/2024_annual_vital_table1.pdf","application/pdf","Annual-summary Table 1; retained for provenance comparison","RAW_OFFICIAL"),
]

def sha256(path):
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()

def main():
    rows = []
    catalog_paths = set()
    for sid, publisher, title, url, rel, media_type, locator, status in SOURCES:
        path = RAW / rel
        if not path.exists():
            raise SystemExit(f"missing raw source: {path}")
        if rel in catalog_paths:
            raise SystemExit(f"duplicate raw path in catalog: {rel}")
        catalog_paths.add(rel)
        rows.append({
            "source_id": sid,
            "publisher": publisher,
            "title": title,
            "source_url": url,
            "raw_file": str(path.relative_to(ROOT)),
            "media_type": media_type,
            "locator": locator,
            "sha256": sha256(path),
            "bytes": path.stat().st_size,
            "status": status,
        })

    actual_paths = {
        str(p.relative_to(RAW))
        for p in RAW.rglob("*")
        if p.is_file()
    }
    if actual_paths != catalog_paths:
        missing = sorted(actual_paths - catalog_paths)
        phantom = sorted(catalog_paths - actual_paths)
        raise SystemExit(
            f"raw/catalog mismatch; unregistered={missing}; missing={phantom}"
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} sources")

if __name__ == "__main__":
    main()
